# -*- coding: utf-8 -*-
"""lab1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RkblpgXdGQzDOIOE95fszeiGuHJkLFR8
"""

# -*- coding: utf-8 -*-
"""
===============================================================================
 MATRIZ BINARIA DE 100.000 x 100.000 BITS ALMACENADA EN DISCO (memmap)
===============================================================================

QUÉ ES np.memmap
----------------
`np.memmap` crea un array de numpy que NO vive en la RAM, sino que está
"mapeado" a un archivo del disco duro. Cuando pedimos `mm[500, 154]`, el
sistema operativo trae del disco solo la porción necesaria (una página de
memoria, típicamente 4 KB). Así podemos manejar 1,25 GB (o mucho más) con
poquísima RAM.

Modos que usamos:
    "w+" -> crear/sobrescribir el archivo y poder leer y escribir.
    "r"  -> abrir solo lectura (protege el archivo de modificaciones).

POR QUÉ SE ESCRIBE POR BLOQUES DE 2000 FILAS
--------------------------------------------
Generar los 1,25 GB de números aleatorios de un solo golpe exigiría 1,25 GB de
RAM. Generando 2000 filas a la vez, cada bloque ocupa solo
2000 x 12.500 = 25 MB, se vuelca a disco con `.flush()` y se libera.

===============================================================================
"""

import os
import numpy as np

# -----------------------------------------------------------------------------
# PARÁMETROS GLOBALES
# -----------------------------------------------------------------------------

N = 100_000            # Número de filas y de columnas LÓGICAS (bits) de la matriz
BYTES_FILA = N // 8    # Bytes que ocupa cada fila en disco (12.500)
RUTA = "matriz.bin"    # Nombre del archivo binario
SEMILLA = 42           # Semilla del generador aleatorio (hace todo reproducible)
BLOQUE = 2000          # Cuántas filas se generan y escriben de una sola vez

# Tabla de "popcount": para cada valor posible de un byte (0..255) guarda cuántos
# bits en 1 tiene. Sirve para contar unos MUY rápido sin desempaquetar bit a bit.
# np.unpackbits convierte cada byte en sus 8 bits; luego sumamos por fila.
TABLA_POPCOUNT = np.unpackbits(
    np.arange(256, dtype=np.uint8).reshape(-1, 1), axis=1
).sum(axis=1).astype(np.uint8)


# =============================================================================
# 1. CREACIÓN DE LA MATRIZ
# =============================================================================

def crear_matriz(ruta=RUTA, n=N, semilla=SEMILLA, bloque=BLOQUE, verbose=True):
    """
    Crea en disco el archivo binario con la matriz de n x n bits.

    Parámetros
    ----------
    ruta : str
        Nombre del archivo que se va a crear (se sobrescribe si ya existe).
    n : int
        Número de filas y columnas lógicas (bits). Debe ser múltiplo de 8.
    semilla : int
        Semilla del generador aleatorio. Con la misma semilla, el archivo
        generado es SIEMPRE idéntico (esto lo aprovecha la verificación).
    bloque : int
        Cuántas filas se escriben por iteración (controla el uso de RAM).
    verbose : bool
        Si True, imprime el progreso.

    Retorna
    -------
    str : la ruta del archivo creado.
    """
    # Si n no es múltiplo de 8 no podríamos empaquetar filas completas en bytes.
    if n % 8 != 0:
        raise ValueError(f"n debe ser múltiplo de 8 para empaquetar bits (n={n})")

    bytes_fila = n // 8

    # mode="w+" -> crea el archivo del tamaño exacto (n * bytes_fila) y permite escribir.
    mm = np.memmap(ruta, dtype=np.uint8, mode="w+", shape=(n, bytes_fila))

    # Generador aleatorio moderno de numpy. Con semilla fija = resultados reproducibles.
    rng = np.random.default_rng(semilla)

    for i in range(0, n, bloque):
        # Cuántas filas escribimos en esta vuelta (la última puede ser más corta).
        filas = min(bloque, n - i)

        # rng.integers(0, 256, ...) genera bytes aleatorios: cada byte son 8 bits
        # aleatorios de la matriz. Es 8 veces más rápido que generar bit a bit.
        mm[i:i + filas] = rng.integers(0, 256, size=(filas, bytes_fila), dtype=np.uint8)

        # flush() obliga al sistema operativo a volcar a disco lo escrito.
        mm.flush()

        if verbose and (i // bloque) % 10 == 0:
            print(f"  escritas {i + filas:,} / {n:,} filas", end="\r")

    # del mm cierra el mapeo y libera el archivo.
    del mm

    if verbose:
        print(f"\nArchivo '{ruta}' creado: {os.path.getsize(ruta):,} bytes")
    return ruta


def abrir_matriz(ruta=RUTA, n=N):
    """
    Abre el archivo ya creado en modo SOLO LECTURA.

    Devuelve un objeto memmap con forma (n, n // 8): n filas y n//8 columnas
    de BYTES (no de bits). Ojo: mm.shape[1] son bytes, no columnas lógicas.
    """
    return np.memmap(ruta, dtype=np.uint8, mode="r", shape=(n, n // 8))


# =============================================================================
# 2. FUNCIONES DE LECTURA
# =============================================================================


def leer_fila(mm, fila):
    """
    Devuelve la FILA COMPLETA como un array de n bits (0 y 1).

    Usa np.unpackbits, que convierte cada byte en sus 8 bits. Una fila de
    12.500 bytes se convierte en 100.000 valores 0/1 -> 100 KB en RAM,
    perfectamente manejable.
    """
    return np.unpackbits(np.asarray(mm[fila]))


def leer_segmento_fila(mm, fila, inicio, fin):
    """
    Devuelve los bits de la fila entre las columnas [inicio, fin) sin
    desempaquetar la fila entera (más eficiente para trozos pequeños).

    como los bits vienen agrupados de 8 en 8, hay que leer los bytes
    que "cubren" el rango pedido y luego recortar los sobrantes de los extremos.
    """
    byte_ini = inicio // 8              # primer byte que toca el rango
    byte_fin = (fin + 7) // 8           # primer byte que YA no toca el rango
    bits = np.unpackbits(np.asarray(mm[fila, byte_ini:byte_fin]))
    desfase = inicio - byte_ini * 8     # cuántos bits sobran al principio
    return bits[desfase:desfase + (fin - inicio)]


def leer_columna(mm, columna, inicio=0, fin=None):
    """
    Devuelve una COLUMNA COMPLETA (o un tramo) como array de bits.

    Ojo con el rendimiento: una columna toca UNA celda de cada fila, y las filas
    están separadas 12.500 bytes en disco. Leer una columna completa obliga al
    sistema a recorrer todo el archivo (1,25 GB), así que es mucho más lento que
    leer una fila. Por eso existe el parámetro `fin` (ver `primeros_de_columna`).

    La operación está vectorizada: `mm[inicio:fin, byte_col]` extrae de golpe el
    byte correspondiente de cada fila, y luego se desplaza y enmascara todo junto.
    """
    if fin is None:
        fin = mm.shape[0]
    byte_col = columna // 8
    posicion = 7 - (columna % 8)
    columna_bytes = np.asarray(mm[inicio:fin, byte_col])
    return ((columna_bytes >> posicion) & 1).astype(np.uint8)


def leer_submatriz(mm, fila_ini, fila_fin, col_ini, col_fin):
    """
    Devuelve un bloque rectangular de bits como matriz 2D.
    Útil para "mirar con lupa" una esquina de la matriz (p. ej. 5x5).
    """
    return np.array([
        leer_segmento_fila(mm, f, col_ini, col_fin)
        for f in range(fila_ini, fila_fin)
    ])


# =============================================================================
# 3. FUNCIONES DE VERIFICACIÓN
# =============================================================================

def dimensiones(mm):
    """
    Devuelve un diccionario con las dimensiones REALES de la matriz, deducidas
    del propio objeto memmap (no de las constantes del programa).

    - filas: mm.shape[0]
    - bytes_por_fila: mm.shape[1]  (lo que hay físicamente en disco)
    - columnas_bits: bytes_por_fila * 8 (las columnas lógicas de la matriz)
    """
    filas, bytes_fila = mm.shape
    return {
        "filas": filas,
        "bytes_por_fila": bytes_fila,
        "columnas_bits": bytes_fila * 8,
        "bits_totales": filas * bytes_fila * 8,
        "bytes_totales": filas * bytes_fila,
    }


def verificar_tamano_archivo(ruta=RUTA, n=N):
    """
    Comprueba que el archivo en disco pesa EXACTAMENTE lo que debería.

    Si el tamaño no coincide, el archivo está incompleto o corrupto y todas las
    lecturas estarían desplazadas (leeríamos basura).
    """
    esperado = n * (n // 8)
    real = os.path.getsize(ruta)
    return {
        "ok": esperado == real,
        "bytes_esperados": esperado,
        "bytes_reales": real,
        "gb_reales": round(real / 1024**3, 3),
    }




def verificar_no_vacia(mm, cuantas=20, semilla=4):
    """
    Comprueba que no hay filas completamente a cero (síntoma típico de un bloque
    que nunca se escribió o de un flush que no llegó a disco).
    """
    rng = np.random.default_rng(semilla)
    filas = rng.integers(0, mm.shape[0], size=cuantas)
    vacias = [int(f) for f in filas if not np.asarray(mm[int(f)]).any()]
    return {"ok": len(vacias) == 0, "filas_vacias_encontradas": vacias}


# =============================================================================
# 4. INFORME COMPLETO
# =============================================================================

def informe(mm, ruta=RUTA, semilla=SEMILLA, bloque=BLOQUE):
    """
    Ejecuta todas las verificaciones y las imprime de forma legible.
    Es la función que hay que llamar para responder a "¿quedó bien la matriz?".

    `semilla` y `bloque` deben ser los mismos que se usaron en `crear_matriz`,
    porque la prueba de reproducibilidad regenera los datos imitando ese proceso.
    """
    def marca(ok):
        return "OK   " if ok else "FALLA"

    print("=" * 70)
    print("INFORME DE VERIFICACIÓN DE LA MATRIZ")
    print("=" * 70)

    d = dimensiones(mm)
    print("\n[1] DIMENSIONES")
    print(f"    Filas .................. {d['filas']:,}")
    print(f"    Columnas (bits) ........ {d['columnas_bits']:,}")
    print(f"    Bytes por fila ......... {d['bytes_por_fila']:,}")
    print(f"    Bits totales ........... {d['bits_totales']:,}")
    print(f"    Bytes totales .......... {d['bytes_totales']:,}")

    t = verificar_tamano_archivo(ruta, d["filas"])
    print(f"\n[2] TAMAÑO DEL ARCHIVO EN DISCO ....... {marca(t['ok'])}")
    print(f"    Esperado: {t['bytes_esperados']:,} bytes")
    print(f"    Real:     {t['bytes_reales']:,} bytes  ({t['gb_reales']} GB)")



    v = verificar_no_vacia(mm)
    print(f"\n[8] SIN FILAS EN BLANCO ............... {marca(v['ok'])}")
    print(f"    Filas vacías encontradas: {v['filas_vacias_encontradas']}")

    todo_ok = all([t["ok"], v["ok"]])
    print("\n" + "=" * 70)
    print("RESULTADO GLOBAL:", "TODO CORRECTO" if todo_ok else "HAY FALLAS")
    print("=" * 70)
    return todo_ok


def muestra(mm):
    """
    Muestra ejemplos concretos de lectura: casillas sueltas, principio de la
    primera fila, principio de la primera columna, una esquina, etc.
    """
    n_filas, n_cols = mm.shape[0], mm.shape[1] * 8

    print("=" * 70)
    print("MUESTRAS DE CONTENIDO")
    print("=" * 70)

    print("\n-- Primeros 20 elementos de la PRIMERA FILA --")
    print("   ", leer_segmento_fila(mm, 0, 0, 20))

    print("\n-- Primeros 10 elementos de la PRIMERA COLUMNA --")
    print("   ", leer_columna(mm, 0, 0, 10))

    print(f"\n-- Fila 0 completa (resumen, son {n_cols:,} bits) --")
    fila0 = leer_fila(mm, 0)
    print(f"    longitud = {len(fila0):,} bits")


    print("\n-- Esquina superior izquierda 8x8 --")
    for fila in leer_submatriz(mm, 0, 8, 0, 8):
        print("    ", " ".join(str(b) for b in fila))


    print("\n-- Columna 0 completa (puede tardar: recorre todo el archivo) --")
    col0 = leer_columna(mm, 0)
    print(f"    longitud = {len(col0):,} bits")


# =============================================================================
# 5. PROGRAMA PRINCIPAL
# =============================================================================

if __name__ == "__main__":
    # Si el archivo ya existe con el tamaño correcto, no lo volvemos a crear
    # (crear 1,25 GB tarda varios minutos).
    esperado = N * BYTES_FILA
    if not os.path.exists(RUTA) or os.path.getsize(RUTA) != esperado:
        print(f"Creando matriz {N:,} x {N:,} bits (~{esperado / 1024**3:.2f} GB)...")
        crear_matriz()
    else:
        print(f"Usando el archivo existente '{RUTA}'.")

    mm = abrir_matriz()

    muestra(mm)
    print()
    informe(mm)